name: Test

on:
  push:
    branches: [main, Release**]
   
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
      - name: get version
        run: |
            echo "run_number ${{ github.run_number }}" 
            echo "version=${{ github.ref_name }}.${{ github.run_number }}" | sed 's/Release-//' >> $GITHUB_ENV
      - name: echo version
        run: |
            echo "version=${{ env.version }}"

            